# Generated by Django 5.0.3 on 2024-04-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='duration',
        ),
        migrations.AddField(
            model_name='habit',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='длительность выполнения'),
        ),
    ]
