# Generated by Django 5.0.3 on 2024-04-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='длительность выполн'),
        ),
    ]
